### ISSUE TITLE
Resamplers Have No Underlying Abstract Class

### ISSUE THREAD

**Issue by whitewhim2718** [QInfer/python-qinfer#74]
__LiuWestResampler__ and __ClusteringResampler__ currently do not have an underlying AbstractClass. This will raise issues with future modifications such as changing the n_particles being re-sampled. A simple ABC should probably be implemented in the future.

**Comment by cgranade** [comment]
Agreed. At least part of the issue is that ``ClusteringResampler`` is embarrassingly old and broken at this point. With that in mind, there's really only one concrete and maintained class that would inherit from the proposed ABC, which has made it a bit less immediately needed. As a part of the 1.0 release, though, I think it does make sense to finally formalize the ``LiuWestResampler`` API using an ABC.

**Comment by whitewhim2718** [comment]
If you have not already begun. I can maybe tackle this next week. I will be busy the rest of this week making posters :-1: .
